### PR TITLE
API: Enable online reconstruction 

### PR DESCRIPTION
**Pull request by carterbox**
## Purpose

Enable online reconstructions; i.e. checking the result without dumping everything from the GPU and adding additional data mid-reconstruction.

## Approach

- Added a new context manager class which keeps the state of the reconstruction on the GPU, provides safe methods for transferring limited data to/from the host, and does appropriate cleanup when the reconstruction ends.
- Added a new PtychoParameters dataclass to organize the scan, probe, object, etc parameters instead of using a dictionary. Named parameters are faster to type and unlike the dictionary, the parameters will always have a default value.
- Added new methods to the PositionOptions class to handle appending new positions to the reconstruction

### Submitter
- [x] Write a helpfully descriptive pull request title.
- [x] Organize changes into logically grouped commits with descriptive commit messages.
- [x] Document all new functions.
- [x] Click 'details' on the readthedocs check to view the updated docs.
- [x] Write tests for new functions or explain why they are not needed.
- [x] Address any complaints from pep8speaks.

### Reviewer
- [x] Actually read all of the code.
- [x] Run the new code yourself; the included tests should make this easy.
- [x] Write a summary of the changes as you understand them.
- [x] Thank the submitter.

### CODE REVIEW

**Comment by carterbox** [comment]
So I ran into a bug while using this API where it is unsafe to call Reconstruction.get_result() before the context is closed because it moves all the parameters back to the host in the middle of the reconstruction (side effects!). I need advice on how to handle this.

The user wants to get the PtychoParameters struct back in its entirety after closing the context, but they cannot be allowed to access it while the context is open. What about tracking whether the context is still open internally and raising an error if get_result() is called before the context is closed?

**Comment by dgursoy** [comment]
Is the context changing the parameters? If not, showing a duplicate when needed might be better than not allowing it when it is open.

**Comment by carterbox** [comment]
Yes. The parameters include both variable (the probe, scan position) and constant (hyperparams) parameters.

**Comment by dgursoy** [comment]
Then like in monitoring iterative algorithms, you can monitor the “states”, which can be pulled or broadcasted at regular intervals.

**Review by stevehenke — APPROVED** [review]
These code changes provide an API for online reconstructions. Based on the context manager pattern, the new interfaces are clean and straightforward to use. The tests are passing. Thank you for your contribution!

**Comment by carterbox** [comment]
Related to #148

**Pull request merged**
